### ISSUE TITLE
Question: How is this file generated/updated?

### ISSUE THREAD

**Issue by jakerockland** [jacqueswww/sublime-vyper#1]
@jacqueswww Was curious if this file is something that can be auto-generated/updated as the Vyper syntax is modified/refined?

**Comment by jacqueswww** [comment]
Hmmm good question, most of these highlighters one just modifies by hand.
And since it's largely based on python it doesn't need much updating.

**Comment by jakerockland** [comment]
Ah that makes sense, figured it was either all auto-generated or something that was slightly modded but was hoping the former may be the case 😅
